/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-empty-object-type */
/**
 * @file generated-types.ts — AUTOGENERATED. DO NOT EDIT.
 *
 * Generated from `schema/region-plugin.schema.json` by
 * `scripts/generate-types.ts`. Re-run with `pnpm generate:types`.
 *
 * Adding or changing a schema field?
 *   1. Edit `schema/region-plugin.schema.json`
 *   2. Run `pnpm generate:types`
 *   3. Commit both files together
 *
 * CI fails on PRs where this file is out of sync with the schema
 * (see `.github/workflows/ci.yml` step "Type-generation drift check").
 *
 * See issue #39.
 */

/**
 * A declarative region configuration file for the Opus Populi civic data platform
 */
export interface RegionPluginFile {
  /**
   * Region identifier (e.g., 'california')
   */
  name: string;
  /**
   * Human-readable region name (e.g., 'California')
   */
  displayName: string;
  /**
   * Brief description of this region's data coverage
   */
  description: string;
  /**
   * Semantic version of this config file
   */
  version: string;
  config: DeclarativeRegionConfig;
}
export interface DeclarativeRegionConfig {
  /**
   * Region identifier (e.g., 'california')
   */
  regionId: string;
  /**
   * Human-readable region name (e.g., 'California')
   */
  regionName: string;
  /**
   * Region description
   */
  description: string;
  /**
   * IANA timezone (e.g., 'America/Los_Angeles')
   */
  timezone: string;
  /**
   * Two-letter US state code (e.g., 'CA')
   */
  stateCode?: string;
  /**
   * Region identifier of this region's parent in the geographic hierarchy. Top-level regions (states, federal) omit this field. Counties set parentRegionId to their state's regionId (e.g., 'california'); cities will set it to their county's regionId. Presence of this field is the canonical signal that a region is a sub-region; the consumer loader uses it to build the region tree.
   */
  parentRegionId?: string;
  /**
   * Census FIPS code: 2 digits for states (e.g., '06' for CA), 5 digits for counties (e.g., '06037' for Los Angeles County — state FIPS + county FIPS), 7 digits for places/cities. This is the canonical join key against the consumer's PostGIS counties/places tables used today for user-to-district placement.
   */
  fipsCode?: string;
  /**
   * Data sources to scrape
   *
   * @minItems 1
   */
  dataSources: [DataSourceConfig, ...DataSourceConfig[]];
  /**
   * Rate limiting defaults
   */
  rateLimit?: {
    requestsPerSecond: number;
    burstSize: number;
  };
  /**
   * Cache TTL in milliseconds
   */
  cacheTtlMs?: number;
  /**
   * Request timeout in milliseconds
   */
  requestTimeoutMs?: number;
  /**
   * Strip leading zeros from representative externalId trailing segment (e.g. ca-assembly-01 → ca-assembly-1). Opt-in; default false. Only needed for regions whose LLM manifests emit zero-padded district numbers.
   */
  normalizeExternalIdDistrict?: boolean;
  /**
   * Regex pattern strings (case-insensitive) matched against scraped representative bio text. Bios matching any pattern are treated as nav junk and discarded. Defaults to no filtering if omitted.
   */
  bioNoisePatterns?: string[];
}
export interface DataSourceConfig {
  /**
   * URL to fetch data from
   */
  url: string;
  /**
   * What type of content this source provides. Daily journals / meeting minutes go under 'meetings' with sourceType=pdf_archive — the consumer partitions by sourceType internally. 'civics' marks a source of region governmental structure, process, and vocabulary; the civics-ingest handler scrapes it and uses the private prompt-service to extract structured shape (chambers, measure types, lifecycle stages with status patterns, glossary) plus a plain-language rewrite for laypeople. Verbatim source text and the AI rewrite are stored together — never one without the other. 'bills' marks a source of individual legislative bills (AB, SB, ACA, SCA, etc.) scraped from an official legislature website; the bills-ingest handler BFS-crawls from the seed URL and extracts one Bill record per detail page. See opuspopuli#686.
   */
  dataType: 'propositions' | 'meetings' | 'representatives' | 'campaign_finance' | 'lobbying' | 'civics' | 'bills';
  /**
   * Natural language description of what to find/extract
   */
  contentGoal: string;
  /**
   * Sub-category for grouping (e.g., 'Assembly', 'Senate')
   */
  category?: string;
  /**
   * Hints to help the AI find the right content
   */
  hints?: string[];
  /**
   * Override rate limit for this specific source
   */
  rateLimitOverride?: number;
  /**
   * 5-field cron expression (minute hour dom month dow) controlling how often this source is synced. The worker applies a deterministic per-source minute offset at registration time to spread load across gov hosts — the minute field you specify is the base, not the exact fire time. Omit to inherit the global daily fallback. Common patterns: '0 2 * * *' daily at 2 AM, '0 2 * * 0' weekly on Sunday, '0 * * * *' hourly.
   */
  syncCadence?: string;
  /**
   * 5-field cron expression for a periodic full status-page sweep of all bills (dataType='bills' only). Runs forceStatusRecheck=true — bypasses the needsStatusRecheck flag and the sourcePublishedAt skip to catch governor actions and off-session changes the journal linker can't see. Per-source minute offset is applied like syncCadence. Typical: '0 2 * * 0' weekly Sunday 2 AM. See #689.
   */
  statusScanCadence?: string;
  /**
   * Source type determines the extraction strategy (default: html_scrape). 'pdf_archive' selects the listing-walk + per-PDF-extract pipeline: the URL is a paginated listing page that links to a series of dated PDF documents, each fetched and parsed (text only at V1) into one Minutes record.
   */
  sourceType?: 'html_scrape' | 'bulk_download' | 'api' | 'pdf' | 'pdf_archive';
  bulk?: BulkDownloadConfig;
  api?: ApiSourceConfig;
  pdf?: PdfSourceConfig;
  pdfArchive?: PdfArchiveConfig;
  billDiscovery?: BillDiscoveryConfig;
  /**
   * Detail page extraction plan: maps domain field names to CSS selectors (string) or structured array configs (object). Supports dot notation and '|attr:name' suffix.
   */
  detailFields?: {
    [k: string]: string | StructuredFieldConfig;
  };
  /**
   * Explicit extraction selectors that bypass AI structural analysis entirely. Use when the page structure is known and stable, or when the local LLM consistently generates wrong selectors.
   */
  staticManifest?: {
    containerSelector: string;
    itemSelector: string;
    fieldMappings: {
      fieldName: string;
      selector: string;
      extractionMethod: string;
      attribute?: string;
      regexPattern?: string;
      regexGroup?: number;
      transform?: {};
      required: boolean;
      defaultValue?: string;
      scope?: 'item' | 'container';
      /**
       * For extractionMethod='structured': child field selectors. Each value is a string shortcut or a ChildFieldConfig object.
       */
      children?: {
        [k: string]: string | ChildFieldConfig;
      };
      [k: string]: any;
    }[];
  };
  /**
   * Crawl depth from the seed URL for sync handlers that walk a site's link graph (currently civics — see opuspopuli#669). 0 (default) = no crawl, fetch only the seed. N = N hops from seed. Crawls are scoped to same host + same path prefix as the seed, HTML responses only.
   */
  crawlDepth?: number;
  /**
   * Cap on total pages a crawler will visit per sync run regardless of crawlDepth. Defaults to 20. Each page costs one LLM call, so this bounds runtime + token spend.
   */
  crawlMaxPages?: number;
  /**
   * Per-source override for the LLM maxTokens generation cap. Useful when a source needs a much longer or shorter output than its siblings (e.g., a 150-term glossary needs ~32000; a short bio prompt finishes well under 2000). Overrides the sync handler's hardcoded default.
   */
  llmMaxTokens?: number;
  /**
   * Per-source override for the LLM provider request timeout (milliseconds). Useful when a single source legitimately runs much longer than the platform-wide default — civics-glossary extraction on qwen3.5:9b can take 15-20 min, while bio gen finishes in 2 min on the same hardware. Overrides the provider's constructor-configured default.
   */
  llmRequestTimeoutMs?: number;
}
export interface BulkDownloadConfig {
  /**
   * File format
   */
  format: 'tsv' | 'csv' | 'zip_tsv' | 'zip_csv';
  /**
   * For ZIP archives: path/glob of target file(s) within the ZIP
   */
  filePattern?: string;
  /**
   * Column delimiter override
   */
  delimiter?: string;
  /**
   * Number of header lines to skip
   */
  headerLines?: number;
  /**
   * Explicit column headers for files without a header row (e.g., FEC bulk files)
   */
  headers?: string[];
  /**
   * Column name mappings: source column name -> domain field name
   */
  columnMappings: {
    [k: string]: string;
  };
  /**
   * Filter expressions applied during parse
   */
  filters?: {
    [k: string]: string;
  };
  /**
   * Records per batch for streaming processing (default: 10000)
   */
  batchSize?: number;
}
export interface ApiSourceConfig {
  /**
   * HTTP method (default: GET)
   */
  method?: 'GET' | 'POST';
  /**
   * Environment variable name containing the API key
   */
  apiKeyEnvVar?: string;
  /**
   * Header name for the API key
   */
  apiKeyHeader?: string;
  pagination?: ApiPaginationConfig;
  /**
   * JSON path to the items array in the response
   */
  resultsPath?: string;
  /**
   * Static query parameters appended to every request
   */
  queryParams?: {
    [k: string]: string;
  };
  /**
   * Field name mappings: API response field -> domain model field (e.g., committee_id -> committeeId)
   */
  fieldMappings?: {
    [k: string]: string;
  };
}
export interface ApiPaginationConfig {
  /**
   * Pagination strategy type
   */
  type: 'offset' | 'cursor' | 'page';
  /**
   * Query parameter name for page/offset
   */
  pageParam?: string;
  /**
   * Query parameter name for page size
   */
  limitParam?: string;
  /**
   * Number of items per page
   */
  limit?: number;
}
export interface PdfSourceConfig {
  /**
   * Skip first N pages (e.g., skip cover page)
   */
  skipPages?: number;
  /**
   * Maximum pages to process (default: all)
   */
  maxPages?: number;
  /**
   * If true, treats the URL as a gateway page and follows the first PDF link
   */
  followPdfLink?: boolean;
}
/**
 * Listing-walk configuration for sourceType=pdf_archive. The page at `url` is treated as a paginated index of dated PDF documents; each linked PDF is fetched, pdf-parsed, and stored as a Minutes record. Cold-start work is bounded by maxNew (default 10) so first-run sync doesn't ingest years of historical archives. Per-document parsing (text → action records) is a downstream backend pass — this block carries no parser DSL.
 */
export interface PdfArchiveConfig {
  /**
   * CSS selector for PDF anchor elements on the listing page. Each match yields a candidate document.
   */
  linkSelector: string;
  /**
   * Regex applied to the link href (falling back to anchor text) to extract the document's date. Capture groups depend on dateFormat.
   */
  datePattern?: string;
  /**
   * Date format hint for interpreting datePattern's captures. Supported: 'MMDDYY' (3 captures: month, day, two-digit year — assumed 20YY), 'YYYY-MM-DD' (3 captures), 'MM/DD/YYYY' (3 captures).
   */
  dateFormat?: string;
  /**
   * Regex against the link href whose match indicates this URL is a revision. Capture group 1 is the revision sequence number (1, 2, ...). Unmatched URLs are revisionSeq=0.
   */
  revisionPattern?: string;
  /**
   * Maximum number of listing pages to walk during one sync cycle. Default: 10.
   */
  maxPages?: number;
  /**
   * Hard cap on number of new documents ingested per sync cycle. Cold-start protection. Default: 10.
   */
  maxNew?: number;
  /**
   * Query parameter name used to paginate the listing page (e.g., 'page'). Omitted when the listing isn't paginated.
   */
  paginationParam?: string;
}
/**
 * Declarative bill discovery for legislature sites that list per-bill nav-hub links on a search results page (e.g. CA leginfo). The bills-ingest handler fetches the seed once, extracts bill IDs with navLinkPattern, and constructs status + votes URLs from the templates — bypassing generic BFS which would exhaust crawlMaxPages with nav-hub links before reaching detail pages.
 */
export interface BillDiscoveryConfig {
  /**
   * Regex string applied to the decoded seed-page HTML to extract bill IDs. Capture group 1 must be the bill ID. Example for CA leginfo: "/faces/billNavClient\\.xhtml\\?bill_id=([^\"&\\s]+)"
   */
  navLinkPattern: string;
  /**
   * URL path + query template for the bill status page. Use {bill_id} as the placeholder; the service prepends the seed origin. Example: "/faces/billStatusClient.xhtml?bill_id={bill_id}"
   */
  statusPageTemplate: string;
  /**
   * URL path + query template for the bill votes page. Same substitution as statusPageTemplate. Example: "/faces/billVotesClient.xhtml?bill_id={bill_id}"
   */
  votesPageTemplate: string;
  /**
   * Optional URL path + query template for the bill text page. When set, the sync fetches this page before LLM extraction to check the 'Date Published' timestamp and skip unchanged bills. Example: "/faces/billTextClient.xhtml?bill_id={bill_id}"
   */
  textPageTemplate?: string;
}
export interface StructuredFieldConfig {
  /**
   * CSS selector matching each repeating item (e.g., '.office-card')
   */
  selector: string;
  /**
   * Child field selectors relative to each item. Each entry is either a string shortcut (e.g. 'h3', 'a|attr:href') or a richer ChildFieldConfig object with extractionMethod / regex / transform.
   */
  children: {
    [k: string]: string | ChildFieldConfig;
  };
  /**
   * If true, extracts all matches as an array (default: true)
   */
  multiple?: boolean;
}
/**
 * Per-child extraction config for structured extraction. Object form supports the same shape as the top-level FieldMapping (selector + extractionMethod + attribute / regex / transform), minus fieldName/required/defaultValue which don't apply at child scope.
 */
export interface ChildFieldConfig {
  /**
   * CSS selector relative to the matched parent item. Optional for regex on full element text.
   */
  selector?: string;
  /**
   * How to extract: 'text', 'attribute', 'regex', 'html', etc.
   */
  extractionMethod?: string;
  /**
   * For extractionMethod='attribute': which attribute to read (e.g. 'href', 'src').
   */
  attribute?: string;
  /**
   * For extractionMethod='regex': the pattern.
   */
  regexPattern?: string;
  /**
   * For extractionMethod='regex': capture group (default: 1).
   */
  regexGroup?: number;
  /**
   * Optional transform applied after extraction (e.g. trim, regex_replace, url_resolve).
   */
  transform?: {};
}
