/**
 * Generate TypeScript types from `schema/region-plugin.schema.json`.
 *
 * Output: `src/cli/lib/generated-types.ts`. Re-run via `pnpm generate:types`
 * (also runs automatically before `pnpm build` via the `prebuild` hook).
 *
 * Single source of truth for the schema-derived TypeScript types — see
 * issue #39. Do NOT edit `generated-types.ts` by hand; edit the JSON
 * Schema and regenerate.
 */

import { compileFromFile } from 'json-schema-to-typescript';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';

const SCHEMA_PATH = join(process.cwd(), 'schema', 'region-plugin.schema.json');
const OUT_PATH = join(
  process.cwd(),
  'src',
  'cli',
  'lib',
  'generated-types.ts',
);

const BANNER = `/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-empty-object-type */
/**
 * @file generated-types.ts — AUTOGENERATED. DO NOT EDIT.
 *
 * Generated from \`schema/region-plugin.schema.json\` by
 * \`scripts/generate-types.ts\`. Re-run with \`pnpm generate:types\`.
 *
 * Adding or changing a schema field?
 *   1. Edit \`schema/region-plugin.schema.json\`
 *   2. Run \`pnpm generate:types\`
 *   3. Commit both files together
 *
 * CI fails on PRs where this file is out of sync with the schema
 * (see \`.github/workflows/ci.yml\` step "Type-generation drift check").
 *
 * See issue #39.
 */
`;

async function main(): Promise<void> {
  const compiled = await compileFromFile(SCHEMA_PATH, {
    // The schema's top-level `title` is "Region Plugin File" — use that
    // as the root type name. Mirror the existing TS naming convention
    // (RegionPluginFile) so the imported name is unchanged.
    bannerComment: '',
    style: { singleQuote: true, tabWidth: 2 },
    additionalProperties: false,
    unknownAny: false,
  });

  writeFileSync(OUT_PATH, BANNER + '\n' + compiled, 'utf-8');
  console.log(`Generated ${OUT_PATH}`);
}

main().catch((err) => {
  console.error('Type generation failed:', err);
  process.exit(1);
});
